### ISSUE TITLE
Feature request: passing account number / project code

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [grisu/grisu-template#11]
Hi Markus,

For NeSI accounting, we will also need to populate the LoadLeveler `# @ account` field for jobs submitted via the grid.

At the RSL level, the `project` keyword is the right place for it (loadleveler.pm than automatically maps the value from the project keyword into the LL account field).

We only need to be able to specify the project keyword from within the Grisu Template Client.

This is closely related to #5, but as this is not part of the job environment but a separate keyword, I'm putting this in as a separate feature request.

This might be solved by introducing a global property that would be populated from a TextField widget: `project = ${ProjectCode}` - that would be passed as `(project=xxx)` in the generated RSL.

Cheers,
Vlad

**Comment by makkus** [comment]
I'm closing this one for now, we managed to get it going so users only have to specify a group and the mapping to a project gets done behind the scenes.
