### ISSUE TITLE
Filelist in right part of the job details panel does not allow to navigate anywhere

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [grisu/grisu-template#4]
Filelist in right part of the job details panel does not allow to navigate anywhere

When I'm viewing the details of a job and switch the right panel from _Preview_ to _File list_, I do not have any option to navigate anywhere - I have an empty list and no navigation tools to move anywhere.

The list in the file list is blank - so I cannot navigate to any directory - does not have the top-level elements (Remote Files: groups, jobs, sites / Local Files) - and does not even have a ".." ... so what the filelist loads appears to be an empty directory detached from the rest of the file space... 

Also, I cannot find the bookmarks arrow that I get in the File selector - that let's me pick from bookmarks and filesystem roots.

**Comment by makkus** [comment]
Ok, wasn't so hard after all, I mixed up something. Anyway, changed the filesystem viewer with the tree-based on. That doesn't have any bookmark support yet, but that could be added easily later on (as an extra node in the virtual filesystem tree).
If you want that, please open another ticket.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks. Working great now. Bookmark support would be great, just submitted as #10
