### ISSUE TITLE
Bug: email_address field sometimes dropped in job submission

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [grisu/grisu-template#6]
Hi,

I was submitting a job (retrying submission several times) with the Email widget and the job got submitted without the email_address RSL element - but WITH the email_on_abort, email_on_execution and email_on_termination elements).

Both the check boxes (when starts, when finishes) were ticked and a valid email address was entered.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Hi,

Additional information: when I look at the job properties, the job is listed with the email address blank:

email_address
email_on_finish true
email_on_start true

**Comment by makkus** [comment]
Ok, just got another report on this one. Had a quick look and it seems it only happens for subsequent submissions. I.e. first time around it works. Submit another job (using the same template), and it doesn't pick it up. 
Something to do with keyboard/action events not being picked up, I'm sure. Will fix for next release.
