### ISSUE TITLE
Bug: when using multiple MonitorCommandlinePanel widgets, only the last one works / gets updates

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [grisu/grisu-template#7]
Hi Markus,

When using multiple MonitorCommandlinePanel widgets (e.g., in a template with multiple tabs, putting one on each tab), only the last one works / gets updates.  The other ones are blank.

Cheers,
Vlad

**Comment by makkus** [comment]
Ok, had a look. This has a very easy workaround, so I'm hesitant to change any code. Just rename the name section

[monitor]

for subsequent Monitor panels, for example, [monitor2]. That should do it.

If you reckon that's not good enough, please re-open.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, all fine with this.  Thanks for the commit fixing this in the RAxML template! Cheers, Vlad
